#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/essay?useUnicode=true&characterEncoding=utf-8
#    driver-class-name: com.mysql.jdbc.Driver
#    sql-script-encoding: UTF-8
#  http:
#    encoding:
#      force: true
#      charset: UTF-8
#      enabled: true
#  mvc:
#    date-format: yyyy-MM-dd
#server:
#  tomcat:
#    uri-encoding: UTF-8
